<html>
<head>
<title>Atendimento On-line</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<body bgcolor="#C7C7C7" topmargin="5" leftmargin="5" rightmargin="5" bottommargin="5">
<table width="100%" border="0" cellspacing="0" cellpadding="0" height="100%">
  <tr>
    <td>
	<iframe name="monitor" src="http://www.midiavale.com/atendimento/default.asp" style="width:100%; height:100%; border:1px inset" frameborder="0"></iframe></td>
  </tr>
</table>
<div id="layer_monitor" style="position:absolute; visibility: hidden; left:6px; top:71px; width:99%; height:75%; z-index:1; overflow: auto; background-color: white">
<iframe name="iframe_monitor" style="width:100%; height=100%" frameborder="0"></iframe></td>
</div>
</body>
</html>
